workflows:
  android-release:
    name: Android Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_URL: "https://example.com"
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release --dart-define=APP_URL=$APP_URL
   artifacts:
        - build/app/outputs/bundle/release/app-release.aab

